spring.application.name=taskmanager

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/taskdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:abcd1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:localdevonlysecretkey123456789012}
app.jwt.expiration=${JWT_EXPIRATION:3600000}